import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { buildMetadata } from "@/lib/seo";

export const metadata = buildMetadata({
  title: "Terms of Service",
  description:
    "Terms of Service for using GetDreamRole resume optimization and related job-search tools.",
  path: "/terms",
});

export default function TermsPage() {
  return (
    <div className="mx-auto max-w-2xl px-6 py-16">
      <div className="mb-10">
        <Link
          href="/"
          className="inline-flex items-center gap-1.5 text-sm text-forge-muted hover:text-forge-text transition-colors"
        >
          <ArrowLeft className="h-4 w-4" />
          Back
        </Link>
      </div>

      <h1 className="font-display text-3xl font-bold text-forge-text mb-2">
        Terms of Service
      </h1>
      <p className="text-forge-muted text-sm mb-10">Last updated: April 2, 2026</p>

      <div className="prose prose-sm max-w-none space-y-8 text-forge-muted leading-relaxed">
        <section>
          <h2 className="font-display text-lg font-semibold text-forge-text mb-3">1. Acceptance of Terms</h2>
          <p>
            By accessing or using GetDreamRole (&quot;the Service&quot;), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.
          </p>
        </section>

        <section>
          <h2 className="font-display text-lg font-semibold text-forge-text mb-3">2. Description of Service</h2>
          <p>
            GetDreamRole provides AI-powered resume optimization tools that analyze your resume against a job description and generate suggestions to improve ATS compatibility. The Service is provided on an as-is basis.
          </p>
        </section>

        <section>
          <h2 className="font-display text-lg font-semibold text-forge-text mb-3">3. One-Time Payment & Access</h2>
          <p>
            Access to the full Service requires a one-time payment of $9.99 USD. This payment grants you lifetime access to the Service on the device and browser where payment was made. Access is stored locally on your device — clearing your browser data will remove your access record.
          </p>
          <p className="mt-3">
            All payments are processed securely by Stripe. We do not offer refunds except where required by applicable law.
          </p>
        </section>

        <section>
          <h2 className="font-display text-lg font-semibold text-forge-text mb-3">4. Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul className="list-disc pl-5 mt-3 space-y-1">
            <li>Use the Service to generate false or misleading resume content</li>
            <li>Attempt to reverse-engineer, scrape, or abuse the Service&apos;s API</li>
            <li>Share, resell, or redistribute access to the Service</li>
            <li>Use the Service for any unlawful purpose</li>
          </ul>
        </section>

        <section>
          <h2 className="font-display text-lg font-semibold text-forge-text mb-3">5. Intellectual Property</h2>
          <p>
            You retain full ownership of your resume content. The optimization suggestions generated by the Service are provided for your personal use. GetDreamRole retains all rights to the Service, its design, and underlying technology.
          </p>
        </section>

        <section>
          <h2 className="font-display text-lg font-semibold text-forge-text mb-3">6. Disclaimer of Warranties</h2>
          <p>
            The Service is provided &quot;as is&quot; without warranty of any kind. GetDreamRole does not guarantee that using the Service will result in job interviews, offers, or any specific employment outcome. Resume optimization suggestions are AI-generated and should be reviewed by you before use.
          </p>
        </section>

        <section>
          <h2 className="font-display text-lg font-semibold text-forge-text mb-3">7. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by law, GetDreamRole shall not be liable for any indirect, incidental, or consequential damages arising from your use of the Service.
          </p>
        </section>

        <section>
          <h2 className="font-display text-lg font-semibold text-forge-text mb-3">8. Changes to Terms</h2>
          <p>
            We may update these terms from time to time. Continued use of the Service after changes constitutes acceptance of the updated terms.
          </p>
        </section>

        <section>
          <h2 className="font-display text-lg font-semibold text-forge-text mb-3">9. Contact</h2>
          <p>
            Questions about these terms? Contact us at{" "}
            <a href="mailto:witchaudiostudios@gmail.com" className="text-forge-accent hover:underline">
              witchaudiostudios@gmail.com
            </a>
          </p>
        </section>
      </div>
    </div>
  );
}
